:page-layout: home
:!sectids:
= AssertJ

[.centered]
[.grid]
== Fluent assertions for java

[.column3]
=== Rich and easy to use

AssertJ provides a rich set of assertions, truly helpful error messages, improves test code readability and is designed to be super easy to use within your favorite IDE.
Get started right away with the one minute starting guide, have a look at some of AssertJ great features or stay up to date with the latest releases.
If you are convinced by AssertJ, you can automatically convert your JUnit assertions to AssertJ.

[.column3]
=== Extensible

You can easily write assertions for your own classes, which will make your test assertions reflect the domain and is a way to use the ubiquitous language in your tests !
We provide an assertion generator to quickly create assertions for your domain model classes.

[.column3]
=== Community driven

AssertJ only exists to help the dev community. We listen to users ideas to provide the most useful assertions.
AssertJ is a fork of the great Fest Assert library which is not maintained anymore.
AssertJ will remain open and free forever.

[.centered]
== AssertJ provides assertions for popular libraries
